version: 2

models:
  - name: src_actor
    description: actor basic info
    columns:
      - name: actor_id
        description: unique key of actor table
        tests:
          - not_null

      - name: first_name
        description: firstname of actor
        tests:
          - not_null

      - name: last_name
        description: lastname of actor
        tests:
          - not_null